My Project: app.web Namespace Reference
app.web Namespace Reference
Functions
getData ()
createMLModel (data)
renderLabel (form)
initializeAL (form, confidence_break=.7)
getNextSetOfImages (form, sampling_method)
prepareResults (images, labels, fromLabelsPage)
home ()
label ()
intermediate ()
intermediatepage (confidence, health_user, blight_user, healthNum_user, blightNum_user)
finalpage (confidence, health_user, blight_user, healthNum_user, blightNum_user, health_test, unhealth_test, healthyNum, unhealthyNum, healthyPct, unhealthyPct, h_prob, b_prob, h_true, b_true)
final ()
feedback (h_list, u_list, h_conf_list, u_conf_list)
Variables
bootstrap = Bootstrap(app)
Detailed Description
@package web
This method is responsible for the inner workings of the different web pages in this application.
Function Documentation
createMLModel()
app.web.createMLModel (data)
Prepares the training set and creates a machine learning model using the training set.
Parameters
----------
data : Pandas DataFrame
    The data that contains the features for each image
Returns
-------
ml_model : ML_Model class object
    ml_model created from the training set.
train_img_names : String
    The names of the images.
Referenced by app.web.getNextSetOfImages(), and app.web.prepareResults().
feedback()
app.web.feedback (h_list, u_list, h_conf_list, u_conf_list)
Operates the feedback(feedback.html) web page.
final()
app.web.final ()
Operates the final(final.html) web page.
References app.web.prepareResults().
finalpage()
app.web.finalpage (confidence, health_user, blight_user, healthNum_user, blightNum_user, health_test, unhealth_test, healthyNum, unhealthyNum, healthyPct, unhealthyPct, h_prob, b_prob, h_true, b_true)
getData()
app.web.getData ()
Gets and returns the csvOut.csv as a DataFrame.
Returns
-------
data : Pandas DataFrame
    The data that contains the features for each image.
Referenced by app.web.getNextSetOfImages(), app.web.initializeAL(), and app.web.prepareResults().
getNextSetOfImages()
app.web.getNextSetOfImages (form, sampling_method)
Uses a sampling method to get the next set of images needed to be labeled.
Parameters
----------
form : LabelForm class object
    form to be used when displaying label.html
sampling_method : SamplingMethods Function
    function that returns the queue and the new test set that does not contain the queue.
Returns
-------
render_template : flask function
    renders the label.html webpage.
References app.web.createMLModel(), app.web.getData(), and app.web.renderLabel().
Referenced by app.web.label().
home()
app.web.home ()
Operates the root (/) and index(index.html) web pages.
initializeAL()
app.web.initializeAL (form, confidence_break = .7)
Initializes the active learning model and sets up the webpage with everything needed to run the application.
Parameters
----------
form : LabelForm class object
    form to be used when displaying label.html
confidence_break : number
    How confident the model is.
Returns
-------
render_template : flask function
    renders the label.html webpage.
References app.web.getData(), and app.web.renderLabel().
Referenced by app.web.label().
intermediate()
app.web.intermediate ()
Operates the intermediate(intermediate.html) web page.
intermediatepage()
app.web.intermediatepage (confidence, health_user, blight_user, healthNum_user, blightNum_user)
label()
app.web.label ()
Operates the label(label.html) web page.
References app.web.getNextSetOfImages(), app.web.initializeAL(), app.web.prepareResults(), and app.web.renderLabel().
prepareResults()
app.web.prepareResults (images, labels, fromLabelsPage)
Creates the new machine learning model and gets the confidence of the machine learning model.
Parameters
----------
form : LabelForm class object
    form to be used when displaying label.html
Returns
-------
render_template : flask function
    renders the appropriate webpage based on new confidence score.
References app.web.createMLModel(), and app.web.getData().
Referenced by app.web.final(), and app.web.label().
renderLabel()
app.web.renderLabel (form)
prepares a render_template to show the label.html web page.
Parameters
----------
form : LabelForm class object
    form to be used when displaying label.html
Returns
-------
render_template : flask function
    renders the label.html webpage.
Referenced by app.web.getNextSetOfImages(), app.web.initializeAL(), and app.web.label().
Variable Documentation
bootstrap
app.web.bootstrap = Bootstrap(app)